version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "30001:3000"
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_ANON_ROLE: wed_anon
      PGRST_JWT_SECRET: secret_key_minimum_32_characters_long
      PGRST_DB_SCHEMAS: api
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
